// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbd_cw7_git_s33988.Data;

#nullable disable

namespace apbd_cw7_git_s33988.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516125419_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbd_cw7_git_s33988.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "I9-14900K ",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "High-end desktop processor, 24 cores, 6.0 GHz boost",
                            Name = "Intel Core i9-14900K"
                        },
                        new
                        {
                            Code = "RTX4090   ",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 2,
                            Description = "Flagship Ada Lovelace GPU, 24 GB GDDR6X",
                            Name = "NVIDIA GeForce RTX 4090"
                        },
                        new
                        {
                            Code = "DDR5-32GB ",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 3,
                            Description = "High-speed DDR5 memory module",
                            Name = "Samsung 32 GB DDR5-5600"
                        },
                        new
                        {
                            Code = "990PRO2TB ",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 4,
                            Description = "Gen4 NVMe SSD, 7450 MB/s read",
                            Name = "Samsung 990 Pro 2 TB NVMe"
                        },
                        new
                        {
                            Code = "I5-13500  ",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "Mid-range desktop processor, 14 cores",
                            Name = "Intel Core i5-13500"
                        });
                });

            modelBuilder.Entity("apbd_cw7_git_s33988.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTEL",
                            FoundationDate = new DateOnly(1968, 7, 18),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "SAMSUNG",
                            FoundationDate = new DateOnly(1969, 1, 13),
                            FullName = "Samsung Electronics Co., Ltd."
                        });
                });

            modelBuilder.Entity("apbd_cw7_git_s33988.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SSD",
                            Name = "Solid State Drive"
                        });
                });

            modelBuilder.Entity("apbd_cw7_git_s33988.Models.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation Ultra",
                            Stock = 3,
                            Warranty = 48,
                            Weight = 18.0
                        });
                });

            modelBuilder.Entity("apbd_cw7_git_s33988.Models.PcComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "I9-14900K ",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "RTX4090   ",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "DDR5-32GB ",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "990PRO2TB ",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "I5-13500  ",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "DDR5-32GB ",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "I9-14900K ",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "RTX4090   ",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "DDR5-32GB ",
                            Amount = 4
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "990PRO2TB ",
                            Amount = 2
                        });
                });

            modelBuilder.Entity("apbd_cw7_git_s33988.Models.Component", b =>
                {
                    b.HasOne("apbd_cw7_git_s33988.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_cw7_git_s33988.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("apbd_cw7_git_s33988.Models.PcComponent", b =>
                {
                    b.HasOne("apbd_cw7_git_s33988.Models.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_cw7_git_s33988.Models.Pc", "Pc")
                        .WithMany("PcComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("apbd_cw7_git_s33988.Models.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("apbd_cw7_git_s33988.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("apbd_cw7_git_s33988.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("apbd_cw7_git_s33988.Models.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
